"""crear_tablas_iniciales

Revision ID: 3ee3405feea5
Revises: 
Create Date: 2026-06-29 01:39:18.482878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee3405feea5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno',
    sa.Column('id_alumno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_matricula', sa.String(length=20), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('email_institucional', sa.String(length=150), nullable=False),
    sa.Column('anio_ingreso', sa.SmallInteger(), nullable=True),
    sa.Column('ciclo_actual', sa.SmallInteger(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_alumno'),
    sa.UniqueConstraint('codigo_matricula'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email_institucional')
    )
    op.create_table('instrumento',
    sa.Column('id_instrumento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('tipo_calificacion', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_instrumento')
    )
    op.create_table('personal',
    sa.Column('id_personal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_personal'),
    sa.UniqueConstraint('email')
    )
    op.create_table('disponibilidad',
    sa.Column('id_slot', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_personal', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_personal'], ['personal.id_personal'], ),
    sa.PrimaryKeyConstraint('id_slot'),
    sa.UniqueConstraint('id_personal', 'fecha', 'hora_inicio', name='uq_slot_personal')
    )
    op.create_table('historia_clinica',
    sa.Column('id_hc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('id_personal_apertura', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_personal_apertura'], ['personal.id_personal'], ),
    sa.PrimaryKeyConstraint('id_hc'),
    sa.UniqueConstraint('id_alumno')
    )
    op.create_table('perfil_psicologico',
    sa.Column('id_perfil', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_instrumento', sa.Integer(), nullable=False),
    sa.Column('nombre_perfil', sa.String(length=100), nullable=False),
    sa.Column('descripcion_base', sa.Text(), nullable=True),
    sa.Column('puntaje_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('puntaje_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nivel_riesgo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_instrumento'], ['instrumento.id_instrumento'], ),
    sa.PrimaryKeyConstraint('id_perfil')
    )
    op.create_table('pregunta',
    sa.Column('id_pregunta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_instrumento', sa.Integer(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.Column('tipo_respuesta', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_instrumento'], ['instrumento.id_instrumento'], ),
    sa.PrimaryKeyConstraint('id_pregunta')
    )
    op.create_table('tamizaje',
    sa.Column('id_tamizaje', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_personal_creador', sa.Integer(), nullable=False),
    sa.Column('id_instrumento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_limite_respuesta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_instrumento'], ['instrumento.id_instrumento'], ),
    sa.ForeignKeyConstraint(['id_personal_creador'], ['personal.id_personal'], ),
    sa.PrimaryKeyConstraint('id_tamizaje')
    )
    op.create_table('opcion_respuesta',
    sa.Column('id_opcion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('texto_opcion', sa.String(length=200), nullable=False),
    sa.Column('valor_numerico', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_pregunta'], ['pregunta.id_pregunta'], ),
    sa.PrimaryKeyConstraint('id_opcion')
    )
    op.create_table('token_acceso',
    sa.Column('id_token', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tamizaje', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_uso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_tamizaje'], ['tamizaje.id_tamizaje'], ),
    sa.PrimaryKeyConstraint('id_token'),
    sa.UniqueConstraint('id_tamizaje', 'id_alumno', name='uq_token_tamizaje_alumno'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('sesion_respuesta',
    sa.Column('id_sesion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_token', sa.Integer(), nullable=False),
    sa.Column('id_tamizaje', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_tamizaje'], ['tamizaje.id_tamizaje'], ),
    sa.ForeignKeyConstraint(['id_token'], ['token_acceso.id_token'], ),
    sa.PrimaryKeyConstraint('id_sesion'),
    sa.UniqueConstraint('id_token')
    )
    op.create_table('respuesta_item',
    sa.Column('id_respuesta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('id_opcion_seleccionada', sa.Integer(), nullable=True),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('valor_numerico', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_opcion_seleccionada'], ['opcion_respuesta.id_opcion'], ),
    sa.ForeignKeyConstraint(['id_pregunta'], ['pregunta.id_pregunta'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion_respuesta.id_sesion'], ),
    sa.PrimaryKeyConstraint('id_respuesta'),
    sa.UniqueConstraint('id_sesion', 'id_pregunta', name='uq_respuesta_sesion_pregunta')
    )
    op.create_table('resultado_tamizaje',
    sa.Column('id_resultado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('id_tamizaje', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.Column('puntaje_emotividad', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('puntaje_actividad', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('puntaje_resonancia', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('puntaje_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('alerta_emotividad_alta', sa.String(length=5), nullable=True),
    sa.Column('ia_diagnostico', sa.Text(), nullable=True),
    sa.Column('ia_caracteristicas', sa.Text(), nullable=True),
    sa.Column('ia_recomendaciones', sa.Text(), nullable=True),
    sa.Column('estado_calculo', sa.String(length=20), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_psicologico.id_perfil'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion_respuesta.id_sesion'], ),
    sa.ForeignKeyConstraint(['id_tamizaje'], ['tamizaje.id_tamizaje'], ),
    sa.PrimaryKeyConstraint('id_resultado'),
    sa.UniqueConstraint('id_sesion')
    )
    op.create_table('cita',
    sa.Column('id_cita', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_slot', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('id_personal', sa.Integer(), nullable=False),
    sa.Column('id_resultado_origen', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('notas_sesion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumno.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_personal'], ['personal.id_personal'], ),
    sa.ForeignKeyConstraint(['id_resultado_origen'], ['resultado_tamizaje.id_resultado'], ),
    sa.ForeignKeyConstraint(['id_slot'], ['disponibilidad.id_slot'], ),
    sa.PrimaryKeyConstraint('id_cita'),
    sa.UniqueConstraint('id_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cita')
    op.drop_table('resultado_tamizaje')
    op.drop_table('respuesta_item')
    op.drop_table('sesion_respuesta')
    op.drop_table('token_acceso')
    op.drop_table('opcion_respuesta')
    op.drop_table('tamizaje')
    op.drop_table('pregunta')
    op.drop_table('perfil_psicologico')
    op.drop_table('historia_clinica')
    op.drop_table('disponibilidad')
    op.drop_table('personal')
    op.drop_table('instrumento')
    op.drop_table('alumno')
    # ### end Alembic commands ###
