"""ampliar_version_instrumento

Revision ID: 8aa5fd0a00f7
Revises: 3ee3405feea5
Create Date: 2026-06-29 13:42:24.168397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa5fd0a00f7'
down_revision: Union[str, None] = '3ee3405feea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
